@csrf
<div class="grid gap-5 lg:grid-cols-4">
    <label class="block lg:col-span-2"><span class="text-sm font-medium">Cliente</span><select name="client_id" class="mt-1 w-full rounded-lg border-slate-300">@foreach($clients as $client)<option value="{{ $client->id }}" @selected(old('client_id',$contract->client_id)==$client->id)>{{ $client->displayName() }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">Numero</span><input name="number" value="{{ old('number',$contract->number) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Stato</span><select name="status" class="mt-1 w-full rounded-lg border-slate-300">@foreach(['draft','sent','awaiting_signature','signed','active','suspended','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(old('status',$contract->status ?: 'draft')===$status)>{{ $status }}</option>@endforeach</select></label>
    <label class="block lg:col-span-2"><span class="text-sm font-medium">Titolo</span><input name="title" value="{{ old('title',$contract->title) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block lg:col-span-2"><span class="text-sm font-medium">Template</span><select name="contract_template_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Nessun template</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected(old('contract_template_id',$contract->contract_template_id)==$template->id)>{{ $template->name }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">Inizio</span><input type="date" name="starts_at" value="{{ old('starts_at', optional($contract->starts_at)->format('Y-m-d') ?: now()->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Fine</span><input type="date" name="ends_at" value="{{ old('ends_at', optional($contract->ends_at)->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Durata mesi</span><input name="duration_months" value="{{ old('duration_months',$contract->duration_months) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="flex items-center gap-2 pt-7"><input type="checkbox" name="auto_renewal" value="1" @checked(old('auto_renewal',$contract->auto_renewal)) class="rounded border-slate-300"> <span class="text-sm">Rinnovo automatico</span></label>
    <label class="block"><span class="text-sm font-medium">Una tantum</span><input name="one_time_amount" value="{{ old('one_time_amount',$contract->one_time_amount ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Canone mensile</span><input name="monthly_fee" value="{{ old('monthly_fee',$contract->monthly_fee ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Canone annuale</span><input name="annual_fee" value="{{ old('annual_fee',$contract->annual_fee ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Pagamento</span><input name="payment_terms" value="{{ old('payment_terms',$contract->payment_terms) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
</div>
<label class="mt-5 block"><span class="text-sm font-medium">Descrizione</span><textarea name="description" rows="3" class="mt-1 w-full rounded-lg border-slate-300">{{ old('description',$contract->description) }}</textarea></label>
<div class="mt-6 rounded-lg border border-slate-200">@for($i=0;$i<5;$i++)@php $item=old("items.$i",$contract->items[$i] ?? null); @endphp<div class="grid grid-cols-12 gap-3 border-b px-4 py-3"><input name="items[{{ $i }}][description]" value="{{ data_get($item,'description') }}" class="col-span-4 rounded-lg border-slate-300 text-sm" placeholder="Servizio incluso"><select name="items[{{ $i }}][agency_service_id]" class="col-span-2 rounded-lg border-slate-300 text-sm"><option value="">-</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(data_get($item,'agency_service_id')==$service->id)>{{ $service->name }}</option>@endforeach</select><input name="items[{{ $i }}][quantity]" value="{{ data_get($item,'quantity',$i===0?1:'') }}" class="rounded-lg border-slate-300 text-sm" placeholder="Qta"><input name="items[{{ $i }}][unit_price]" value="{{ data_get($item,'unit_price',$i===0?0:'') }}" class="rounded-lg border-slate-300 text-sm" placeholder="Prezzo"><input name="items[{{ $i }}][vat_rate]" value="{{ data_get($item,'vat_rate',22) }}" class="rounded-lg border-slate-300 text-sm" placeholder="IVA"><select name="items[{{ $i }}][billing_type]" class="col-span-2 rounded-lg border-slate-300 text-sm">@foreach(['one_time'=>'Una tantum','monthly'=>'Mensile','annual'=>'Annuale'] as $k=>$v)<option value="{{ $k }}" @selected(data_get($item,'billing_type','one_time')===$k)>{{ $v }}</option>@endforeach</select></div>@endfor</div>
<label class="mt-5 block"><span class="text-sm font-medium">Condizioni contrattuali / contenuto libero</span><textarea name="terms" rows="8" class="mt-1 w-full rounded-lg border-slate-300">{{ old('terms',$contract->terms) }}</textarea></label>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('admin.contracts.index') }}" class="rounded-lg border px-4 py-2 text-sm">Annulla</a><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Salva</button></div>
